export const FETCH_POKEMON = "FETCH_POKEMON";
export const RECEIVE_POKEMON = "RECEIVE_POKEMON";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const RECEIVE_POKEMON_INFO = "RECEIVE_POKEMON_INFO";
export const DISPLAY_NEXT_BATCH = "DISPLAY_NEXT_BATCH";
export const INPUT_VALUE = "INPUT_VALUE";
export const UPDATE_QUERIED_POKEMON = "UPDATE_QUERIED_POKEMON";
